eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
okta:
  oauth2:
    issuer: https://dev-51055711.okta.com/oauth2/default
    audience: api://default


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:  
  tracing:
    enabled: true
    sampling:
      probability: 1.0

okta:
  oauth2:
    issuer: https://dev-51055711.okta.com/oauth2/default
    audience: api://default

spring:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
    base-url: http://localhost:9411

logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG
